ci: fix env secret ref and add debug

diff --git a/.github/workflows/autoupdate.yml b/.github/workflows/autoupdate.yml
--- a/.github/workflows/autoupdate.yml
+++ b/.github/workflows/autoupdate.yml
@@ -26,8 +26,12 @@ jobs:
 
       - name: Run brew livecheck and bump formulas
         run: |
-          # Set up GitHub PAT for opening PRs
-          echo "HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}" >> "$GITHUB_ENV"
+          set -o errexit  # abort on nonzero exitstatus
+          set -o nounset  # abort on unbound variable
+          set -o pipefail # don't hide errors within pipes
+          if [ "${RUNNER_DEBUG:-}" = "1" ]; then
+            set -o xtrace # print each command execution
+          fi
 
           # Find formulas to check
           brew tap nikaro/tap
@@ -66,6 +70,7 @@ jobs:
             fi
           done
         env:
+          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
           HOMEBREW_NO_ENV_HINTS: 1
           HOMEBREW_NO_AUTO_UPDATE: 1
           HOMEBREW_NO_INSTALL_CLEANUP: 1
